title: "Lazy Reader"
description: "Đọc tài liệu tiếng Việt"
baseurl: ""
url: ""
permalink: /bai/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

exclude:
  - functions/
  - docs/
  - Gemfile
  - Gemfile.lock
  - .dev.vars
  - .dev.vars.example
  - vendor/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
